addSbtPlugin("org.jetbrains"      % "sbt-ide-settings"    % "1.1.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager" % "1.7.6")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"        % "0.14.7")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"             % "0.3.4")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager" % "1.7.6")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"        % "0.9.27")
addSbtPlugin("com.github.sbt"     % "sbt-jacoco"          % "3.0.3")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"        % "2.4.0")
